USE [master]

/****** Object:  Database [MedicalCorporation]    Script Date: 23.12.2021 19:35:12 ******/
CREATE DATABASE [MedicalCorporation]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

ALTER DATABASE [MedicalCorporation] SET COMPATIBILITY_LEVEL = 150

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MedicalCorporation].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [MedicalCorporation] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [MedicalCorporation] SET ANSI_NULLS OFF 

ALTER DATABASE [MedicalCorporation] SET ANSI_PADDING OFF 

ALTER DATABASE [MedicalCorporation] SET ANSI_WARNINGS OFF 

ALTER DATABASE [MedicalCorporation] SET ARITHABORT OFF 

ALTER DATABASE [MedicalCorporation] SET AUTO_CLOSE OFF 

ALTER DATABASE [MedicalCorporation] SET AUTO_SHRINK OFF 

ALTER DATABASE [MedicalCorporation] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [MedicalCorporation] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [MedicalCorporation] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [MedicalCorporation] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [MedicalCorporation] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [MedicalCorporation] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [MedicalCorporation] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [MedicalCorporation] SET  DISABLE_BROKER 

ALTER DATABASE [MedicalCorporation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [MedicalCorporation] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [MedicalCorporation] SET TRUSTWORTHY OFF 

ALTER DATABASE [MedicalCorporation] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [MedicalCorporation] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [MedicalCorporation] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [MedicalCorporation] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [MedicalCorporation] SET RECOVERY FULL 

ALTER DATABASE [MedicalCorporation] SET  MULTI_USER 

ALTER DATABASE [MedicalCorporation] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [MedicalCorporation] SET DB_CHAINING OFF 

ALTER DATABASE [MedicalCorporation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [MedicalCorporation] SET TARGET_RECOVERY_TIME = 60 SECONDS 

ALTER DATABASE [MedicalCorporation] SET DELAYED_DURABILITY = DISABLED 

ALTER DATABASE [MedicalCorporation] SET ACCELERATED_DATABASE_RECOVERY = OFF  

EXEC sys.sp_db_vardecimal_storage_format N'MedicalCorporation', N'ON'

ALTER DATABASE [MedicalCorporation] SET QUERY_STORE = OFF
